[package]
name = "sia_viewer"
version = "0.1.0"
authors = ["Andreas Strømberg"]
edition = "2018"

[dependencies]
image = "0.23.11"
native-dialog = "0.4.3"
kiss3d = "0.27"
nalgebra = "0.23.0"
nfd2 = "0.2.3"
sia_parser = {path = "../sia_parser"}
obj-exporter = "0.2.0"