[package]
name = "sia_viewer"
version = "0.1.0"
authors = ["Andreas Strømberg"]
edition = "2018"

[dependencies]
kiss3d = "0.25.0"
nalgebra = "0.22.0"
nfd2 = "0.2.1"
sia_parser = {path = "../sia_parser"}